#!/bin/sh
JAVA_FLAGS="--add-opens=java.base/java.util=ALL-UNNAMED"
JAVA_RUN=$APPDIR/jre/bin/java
JAVA_LOG_CONFIG=$APPDIR/logger.properties
$JAVA_RUN $JAVA_FLAGS $JAVA_EXTRA_GFX_FLAGS "-Djava.util.logging.config.file=$JAVA_LOG_CONFIG" "-Djava.library.path=$APPDIR" -jar $APPDIR/japagoge*.jar $@
